import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../Components/PartsofHomePage/header'
import React,{useEffect,useState} from 'react'
import { useMousePosition } from '@/Functions/functions'
import { GetScreenType } from '@/Functions/functions'
import { motion } from "framer-motion";
import useScreenType from 'react-screentype-hook'

const inter = Inter({ subsets: ['latin'] })

 const Home=()=> {
   const god = true;
   const [mobile,setMobile]=useState(true)
   const x = useMousePosition() as null|any
    

   const xoffset = x.x - 20;
   const yoffset = x.y - 20;
 
   useEffect(() => {
    if (typeof window !== 'undefined') {
      
      //Cause of Next SSR you gotta do this baloney
     const isMobileDevice = () => /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
      console.log(isMobileDevice())
      if (isMobileDevice()) {
        setMobile(false)

      }
    }
   
 })
  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      {mobile&& (
        < div style={{
        position: "absolute",
        left: `${xoffset}px`,
        top: `${yoffset}px`,
        width: 50,
        height: 50,
        borderWidth: 1,
        borderColor: "white",
        borderRadius: 40,
        pointerEvents: "none"
      }}>
    </div>
      )
      }
      
      <Header text="welcome to the website!" />
      <main>
        <div>
         
          

        </div>

      

       
      </main>


    </>
  )
 }
export default Home;