import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import Header from '../Components/PartsofHomePage/header'
import React,{useEffect,useState} from 'react'
import { useMousePosition } from '@/Functions/functions'
import { GetScreenType } from '@/Functions/functions'
import { motion } from "framer-motion";
import useScreenType from 'react-screentype-hook'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

 const Home=()=> {
   const god = true;
   const [extra,setExtraDesc]=useState(false)
   const [mobile,setMobile]=useState(true)
   const x = useMousePosition() as null|any
    

   const xoffset = x.x - 20;
   const yoffset = x.y - 20;
 
   useEffect(() => {
    if (typeof window !== 'undefined') {
      
      //Cause of Next SSR you gotta do this baloney
     const isMobileDevice = () => /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
      console.log(isMobileDevice())
      if (isMobileDevice()) {
        setMobile(false)

      }
    }
   
 })
  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      {mobile&& (
        < div style={{
        position: "absolute",
        left: `${xoffset}px`,
        top: `${yoffset}px`,
        width: 50,
        height: 50,
        borderWidth: 1,
        borderColor: "white",
        borderRadius: 40,
        pointerEvents: "none"
      }}>
    </div>
      )
      }
      
      <Header  />
      
      <main>
       
    
        <div className="  h-1/2 w-1/2 border-white border-2   m-auto left-0 right-0 mt-10 lg:mt-20 ">
          
          <motion.div animate={{ x: 40,y:25 ,margin:"auto" }} className="mb-4 lg:mb-60 " >
                    <p className="font-mono text-centre  m-auto" >Welcome!</p>
                </motion.div>
                
          <motion.div animate={{y:20}} className="mb-4  " >

          <Link href="/about" className=" flex border-white border-2 mt-10">
          <p className="m-auto font-mono">about</p>
            </Link>
         
          
          <Link href="/about" className=" flex border-white border-2 mt-10 mb-40">
          <p className="m-auto font-mono">in the now (need to make real)</p>
          </Link>
          </motion.div>
            
          </div>
    

      

       
      </main>


    </>
  )
 }
export default Home;